.PHONY: clean %.revtex
# .SILENT: one-bib sub-bibs

%.pdf: %.tex $(DEPENDS)
	# @echo Unomment $@.tex bibliography commands\;
	# sed -i 's/^%\s*\(\\bibliography\)/\1/' $<
	rubber --synctex -f --pdf -s $<
	rubber-info --check $<

%.revtex: %.tex
	@echo "Generate gitrevision.tex"
	@echo "% Autogenerated (see latex.mk), do not edit" > gitrevision.tex
	@echo "\\\\newcommand{\\\\revisiondate}{`git log -1 --format=\"%ad\" --date=short $<`}" >> gitrevision.tex
	@echo "\\\\newcommand{\\\\revisiontag}{`git describe --dirty --abbrev --always --tags`}" >> gitrevision.tex
	@echo "\\\\newcommand{\\\\revisiononeline}{`git log -1 --oneline $<`}" >> gitrevision.tex
	@echo "\\\\newcommand{\\\\compiledfile}{$^}" >> gitrevision.tex
	@echo "\\\\newcommand{\\\\revisionhash}{`git log -1 --format=\"%h\" $<`(`git describe --dirty --abbrev --always --tags`)}" >> gitrevision.tex # obsolete, garde pour rétrocompatitibilité

clean:
	rm -rfv *.ps *.aux *.bbl *.blg *.log *.toc *.snm *.out *.nav tags *.vtc *.dvi *.sta *.lof *.lot *.bcf *.synctex.gz *.revtex *.acn *.idx *.ntn *.run.xml *.xdy *.nlg *.not *.alg *.gls *.acr *.glg *.ilg *.ind *.ist *.rubbercache

